import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
// Shim import.meta.url for ESM-only packages (e.g. @anthropic-ai/claude-agent-sdk) bundled into CJS
// __filename is undefined in Obsidian's plugin loader (no CJS module wrapper injected),
// so wrap in a try/catch and fall back to a dummy file URL.
// createRequire() only uses the base URL for relative resolution; built-in modules ignore it.
const __importMetaUrl = (function() { try { return require('url').pathToFileURL(__filename).href; } catch (_) { return 'file:///obsidian-plugin.js'; } })();
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	outfile: 'main.js',
	format: 'cjs',
	platform: 'node',
	target: 'node16',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	minify: prod,
	define: {
		'process.env.NODE_ENV': prod ? '"production"' : '"development"',
		'import.meta.url': '__importMetaUrl',
	}
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
